### ISSUE TITLE
TypeError: responseHandlder is not a function

### ISSUE THREAD

**Issue by shuliangfu** [kawanet/express-intercept#1]
const { requestHandler, responseHandlder } = require("express-intercept");

TypeError: responseHandlder is not a function

console.log('responseHandlder', responseHandlder);
responseHandlder undefined

console.log('requestHandler', requestHandler);
requestHandler [Function: requestHandler]

**Comment by shuliangfu** [comment]
Example error
responseHandlder -> responseHandler

**Comment by kawanet** [comment]
Thanks! 😨 
```diff
- const {requestHandler, responseHandlder} = require("express-intercept");
+ const {requestHandler, responseHandler} = require("express-intercept");
```

**Comment by shuliangfu** [comment]
Ok
